/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_INTERNED_DATA_INTERNED_DATA_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_INTERNED_DATA_INTERNED_DATA_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"

DEJAVIEW_PB_MSG_DECL(dejaview_protos_Callstack);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_DebugAnnotationName);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_DebugAnnotationValueTypeName);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_EventCategory);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_EventName);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_Frame);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_HistogramName);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedGpuRenderStageSpecification);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedGraphicsContext);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedString);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedV8Isolate);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedV8JsFunction);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedV8JsScript);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedV8String);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InternedV8WasmScript);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_LogMessageBody);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_Mapping);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_NetworkPacketContext);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ProfiledFrameSymbols);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_SourceLocation);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_UnsymbolizedSourceLocation);

DEJAVIEW_PB_MSG(dejaview_protos_InternedData);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_EventCategory,
                  event_categories,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_EventName,
                  event_names,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_DebugAnnotationName,
                  debug_annotation_names,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_DebugAnnotationValueTypeName,
                  debug_annotation_value_type_names,
                  27);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_SourceLocation,
                  source_locations,
                  4);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_UnsymbolizedSourceLocation,
                  unsymbolized_source_locations,
                  28);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_LogMessageBody,
                  log_message_body,
                  20);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_HistogramName,
                  histogram_names,
                  25);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  build_ids,
                  16);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  mapping_paths,
                  17);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  source_paths,
                  18);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  function_names,
                  5);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_ProfiledFrameSymbols,
                  profiled_frame_symbols,
                  21);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_Mapping,
                  mappings,
                  19);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_Frame,
                  frames,
                  6);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_Callstack,
                  callstacks,
                  7);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  vulkan_memory_keys,
                  22);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedGraphicsContext,
                  graphics_contexts,
                  23);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedGpuRenderStageSpecification,
                  gpu_specifications,
                  24);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  kernel_symbols,
                  26);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  debug_annotation_string_values,
                  29);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_NetworkPacketContext,
                  packet_context,
                  30);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedV8String,
                  v8_js_function_name,
                  31);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedV8JsFunction,
                  v8_js_function,
                  32);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedV8JsScript,
                  v8_js_script,
                  33);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedV8WasmScript,
                  v8_wasm_script,
                  34);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedV8Isolate,
                  v8_isolate,
                  35);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  protolog_string_args,
                  36);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  protolog_stacktrace,
                  37);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  viewcapture_package_name,
                  38);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  viewcapture_window_name,
                  39);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  viewcapture_view_id,
                  40);
DEJAVIEW_PB_FIELD(dejaview_protos_InternedData,
                  MSG,
                  dejaview_protos_InternedString,
                  viewcapture_class_name,
                  41);

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_INTERNED_DATA_INTERNED_DATA_PZC_H_
