/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_TRACK_EVENT_TRACK_EVENT_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_TRACK_EVENT_TRACK_EVENT_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"

DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeActiveProcesses);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeApplicationStateInfo);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeCompositorSchedulerState);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeContentSettingsEventInfo);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeFrameReporter);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeHistogramSample);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeKeyedService);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeLatencyInfo);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeLegacyIpc);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeMessagePump);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeMojoEventInfo);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeRendererSchedulerState);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeUserEvent);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeWindowHandleEventInfo);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_DebugAnnotation);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_LogMessage);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_PixelModemEventInsight);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_Screenshot);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_SourceLocation);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_TaskExecution);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_TrackEvent_LegacyEvent);

DEJAVIEW_PB_ENUM_IN_MSG(dejaview_protos_TrackEvent, Type){
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent,
                                  TYPE_UNSPECIFIED) = 0,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent,
                                  TYPE_SLICE_BEGIN) = 1,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent,
                                  TYPE_SLICE_END) = 2,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent, TYPE_INSTANT) = 3,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent, TYPE_COUNTER) = 4,
};

DEJAVIEW_PB_ENUM_IN_MSG(dejaview_protos_TrackEvent_LegacyEvent, FlowDirection){
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  FLOW_UNSPECIFIED) = 0,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  FLOW_IN) = 1,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  FLOW_OUT) = 2,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  FLOW_INOUT) = 3,
};

DEJAVIEW_PB_ENUM_IN_MSG(dejaview_protos_TrackEvent_LegacyEvent,
                        InstantEventScope){
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  SCOPE_UNSPECIFIED) = 0,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  SCOPE_GLOBAL) = 1,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  SCOPE_PROCESS) = 2,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_TrackEvent_LegacyEvent,
                                  SCOPE_THREAD) = 3,
};

DEJAVIEW_PB_MSG(dejaview_protos_EventName);
DEJAVIEW_PB_FIELD(dejaview_protos_EventName, VARINT, uint64_t, iid, 1);
DEJAVIEW_PB_FIELD(dejaview_protos_EventName, STRING, const char*, name, 2);

DEJAVIEW_PB_MSG(dejaview_protos_EventCategory);
DEJAVIEW_PB_FIELD(dejaview_protos_EventCategory, VARINT, uint64_t, iid, 1);
DEJAVIEW_PB_FIELD(dejaview_protos_EventCategory, STRING, const char*, name, 2);

DEJAVIEW_PB_MSG(dejaview_protos_TrackEventDefaults);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEventDefaults,
                  VARINT,
                  uint64_t,
                  track_uuid,
                  11);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEventDefaults,
                  VARINT,
                  uint64_t,
                  extra_counter_track_uuids,
                  31);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEventDefaults,
                  VARINT,
                  uint64_t,
                  extra_double_counter_track_uuids,
                  45);

DEJAVIEW_PB_MSG(dejaview_protos_TrackEvent);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  uint64_t,
                  category_iids,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  STRING,
                  const char*,
                  categories,
                  22);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent, VARINT, uint64_t, name_iid, 10);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent, STRING, const char*, name, 23);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  enum dejaview_protos_TrackEvent_Type,
                  type,
                  9);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent, VARINT, uint64_t, track_uuid, 11);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  counter_value,
                  30);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  FIXED64,
                  double,
                  double_counter_value,
                  44);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  uint64_t,
                  extra_counter_track_uuids,
                  31);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  extra_counter_values,
                  12);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  uint64_t,
                  extra_double_counter_track_uuids,
                  45);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  FIXED64,
                  double,
                  extra_double_counter_values,
                  46);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  uint64_t,
                  flow_ids_old,
                  36);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent, FIXED64, uint64_t, flow_ids, 47);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  uint64_t,
                  terminating_flow_ids_old,
                  42);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  FIXED64,
                  uint64_t,
                  terminating_flow_ids,
                  48);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_DebugAnnotation,
                  debug_annotations,
                  4);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_TaskExecution,
                  task_execution,
                  5);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_LogMessage,
                  log_message,
                  21);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeCompositorSchedulerState,
                  cc_scheduler_state,
                  24);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeUserEvent,
                  chrome_user_event,
                  25);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeKeyedService,
                  chrome_keyed_service,
                  26);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeLegacyIpc,
                  chrome_legacy_ipc,
                  27);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeHistogramSample,
                  chrome_histogram_sample,
                  28);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeLatencyInfo,
                  chrome_latency_info,
                  29);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeFrameReporter,
                  chrome_frame_reporter,
                  32);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeApplicationStateInfo,
                  chrome_application_state_info,
                  39);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeRendererSchedulerState,
                  chrome_renderer_scheduler_state,
                  40);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeWindowHandleEventInfo,
                  chrome_window_handle_event_info,
                  41);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeContentSettingsEventInfo,
                  chrome_content_settings_event_info,
                  43);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeActiveProcesses,
                  chrome_active_processes,
                  49);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_Screenshot,
                  screenshot,
                  50);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_PixelModemEventInsight,
                  pixel_modem_event_insight,
                  51);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_SourceLocation,
                  source_location,
                  33);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  uint64_t,
                  source_location_iid,
                  34);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeMessagePump,
                  chrome_message_pump,
                  35);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_ChromeMojoEventInfo,
                  chrome_mojo_event_info,
                  38);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  timestamp_delta_us,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  timestamp_absolute_us,
                  16);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  thread_time_delta_us,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  thread_time_absolute_us,
                  17);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  thread_instruction_count_delta,
                  8);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  VARINT,
                  int64_t,
                  thread_instruction_count_absolute,
                  20);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent,
                  MSG,
                  dejaview_protos_TrackEvent_LegacyEvent,
                  legacy_event,
                  6);

DEJAVIEW_PB_MSG(dejaview_protos_TrackEvent_LegacyEvent);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  uint64_t,
                  name_iid,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  int32_t,
                  phase,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  int64_t,
                  duration_us,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  int64_t,
                  thread_duration_us,
                  4);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  int64_t,
                  thread_instruction_delta,
                  15);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  uint64_t,
                  unscoped_id,
                  6);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  uint64_t,
                  local_id,
                  10);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  uint64_t,
                  global_id,
                  11);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  STRING,
                  const char*,
                  id_scope,
                  7);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  bool,
                  use_async_tts,
                  9);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  uint64_t,
                  bind_id,
                  8);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  bool,
                  bind_to_enclosing,
                  12);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  enum dejaview_protos_TrackEvent_LegacyEvent_FlowDirection,
                  flow_direction,
                  13);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  enum dejaview_protos_TrackEvent_LegacyEvent_InstantEventScope,
                  instant_event_scope,
                  14);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  int32_t,
                  pid_override,
                  18);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackEvent_LegacyEvent,
                  VARINT,
                  int32_t,
                  tid_override,
                  19);

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_TRACK_EVENT_TRACK_EVENT_PZC_H_
