/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_TRACK_EVENT_TRACK_DESCRIPTOR_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_TRACK_EVENT_TRACK_DESCRIPTOR_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"

DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeProcessDescriptor);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeThreadDescriptor);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_CounterDescriptor);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ProcessDescriptor);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ThreadDescriptor);

DEJAVIEW_PB_MSG(dejaview_protos_TrackDescriptor);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor, VARINT, uint64_t, uuid, 1);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  VARINT,
                  uint64_t,
                  parent_uuid,
                  5);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  STRING,
                  const char*,
                  name,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  STRING,
                  const char*,
                  static_name,
                  10);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  MSG,
                  dejaview_protos_ProcessDescriptor,
                  process,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  MSG,
                  dejaview_protos_ChromeProcessDescriptor,
                  chrome_process,
                  6);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  MSG,
                  dejaview_protos_ThreadDescriptor,
                  thread,
                  4);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  MSG,
                  dejaview_protos_ChromeThreadDescriptor,
                  chrome_thread,
                  7);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  MSG,
                  dejaview_protos_CounterDescriptor,
                  counter,
                  8);
DEJAVIEW_PB_FIELD(dejaview_protos_TrackDescriptor,
                  VARINT,
                  bool,
                  disallow_merging_with_system_tracks,
                  9);

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_TRACK_EVENT_TRACK_DESCRIPTOR_PZC_H_
