/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_COMMON_BUILTIN_CLOCK_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_COMMON_BUILTIN_CLOCK_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"

DEJAVIEW_PB_ENUM(dejaview_protos_BuiltinClock){
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_UNKNOWN) = 0,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_REALTIME) = 1,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_REALTIME_COARSE) = 2,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_MONOTONIC) = 3,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_MONOTONIC_COARSE) = 4,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_MONOTONIC_RAW) = 5,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_BOOTTIME) = 6,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_TSC) = 9,
    DEJAVIEW_PB_ENUM_ENTRY(dejaview_protos_BUILTIN_CLOCK_MAX_ID) = 63,
};

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_COMMON_BUILTIN_CLOCK_PZC_H_
