/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_COMMON_DATA_SOURCE_DESCRIPTOR_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_COMMON_DATA_SOURCE_DESCRIPTOR_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"

DEJAVIEW_PB_MSG_DECL(dejaview_protos_FtraceDescriptor);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_GpuCounterDescriptor);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_TrackEventDescriptor);

DEJAVIEW_PB_MSG(dejaview_protos_DataSourceDescriptor);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  STRING,
                  const char*,
                  name,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  VARINT,
                  uint64_t,
                  id,
                  7);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  VARINT,
                  bool,
                  will_notify_on_stop,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  VARINT,
                  bool,
                  will_notify_on_start,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  VARINT,
                  bool,
                  handles_incremental_state_clear,
                  4);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  VARINT,
                  bool,
                  no_flush,
                  9);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  MSG,
                  dejaview_protos_GpuCounterDescriptor,
                  gpu_counter_descriptor,
                  5);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  MSG,
                  dejaview_protos_TrackEventDescriptor,
                  track_event_descriptor,
                  6);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceDescriptor,
                  MSG,
                  dejaview_protos_FtraceDescriptor,
                  ftrace_descriptor,
                  8);

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_COMMON_DATA_SOURCE_DESCRIPTOR_PZC_H_
