/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_CLOCK_SNAPSHOT_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_CLOCK_SNAPSHOT_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"
#include "dejaview/public/protos/common/builtin_clock.pzc.h"

DEJAVIEW_PB_MSG_DECL(dejaview_protos_ClockSnapshot_Clock);

DEJAVIEW_PB_ENUM_IN_MSG(dejaview_protos_ClockSnapshot_Clock, BuiltinClocks){
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  UNKNOWN) = 0,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  REALTIME) = 1,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  REALTIME_COARSE) = 2,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  MONOTONIC) = 3,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  MONOTONIC_COARSE) = 4,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  MONOTONIC_RAW) = 5,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  BOOTTIME) = 6,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_ClockSnapshot_Clock,
                                  BUILTIN_CLOCK_MAX_ID) = 63,
};

DEJAVIEW_PB_MSG(dejaview_protos_ClockSnapshot);
DEJAVIEW_PB_FIELD(dejaview_protos_ClockSnapshot,
                  MSG,
                  dejaview_protos_ClockSnapshot_Clock,
                  clocks,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_ClockSnapshot,
                  VARINT,
                  enum dejaview_protos_BuiltinClock,
                  primary_trace_clock,
                  2);

DEJAVIEW_PB_MSG(dejaview_protos_ClockSnapshot_Clock);
DEJAVIEW_PB_FIELD(dejaview_protos_ClockSnapshot_Clock,
                  VARINT,
                  uint32_t,
                  clock_id,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_ClockSnapshot_Clock,
                  VARINT,
                  uint64_t,
                  timestamp,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_ClockSnapshot_Clock,
                  VARINT,
                  bool,
                  is_incremental,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_ClockSnapshot_Clock,
                  VARINT,
                  uint64_t,
                  unit_multiplier_ns,
                  4);

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_CLOCK_SNAPSHOT_PZC_H_
