/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_CONFIG_DATA_SOURCE_CONFIG_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_CONFIG_DATA_SOURCE_CONFIG_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"

DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidGameInterventionListConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidInputEventConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidLogConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidPolledStateConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidPowerConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidSdkSyspropGuardConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_AndroidSystemPropertyConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ChromeConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_EtwConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_FtraceConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_GpuCounterConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_HeapprofdConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InodeFileConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_InterceptorConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_JavaHprofConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_NetworkPacketTraceConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_PackagesListConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_PerfEventConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_PixelModemConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ProcessStatsConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_ProtoLogConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_StatsdTracingConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_SurfaceFlingerLayersConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_SurfaceFlingerTransactionsConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_SysStatsConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_SystemInfoConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_TestConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_TrackEventConfig);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_V8Config);
DEJAVIEW_PB_MSG_DECL(dejaview_protos_VulkanMemoryConfig);

DEJAVIEW_PB_ENUM_IN_MSG(dejaview_protos_DataSourceConfig, SessionInitiator){
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_DataSourceConfig,
                                  SESSION_INITIATOR_UNSPECIFIED) = 0,
    DEJAVIEW_PB_ENUM_IN_MSG_ENTRY(dejaview_protos_DataSourceConfig,
                                  SESSION_INITIATOR_TRUSTED_SYSTEM) = 1,
};

DEJAVIEW_PB_MSG(dejaview_protos_DataSourceConfig);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  STRING,
                  const char*,
                  name,
                  1);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  uint32_t,
                  target_buffer,
                  2);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  uint32_t,
                  trace_duration_ms,
                  3);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  bool,
                  prefer_suspend_clock_for_duration,
                  122);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  uint32_t,
                  stop_timeout_ms,
                  7);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  bool,
                  enable_extra_guardrails,
                  6);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  enum dejaview_protos_DataSourceConfig_SessionInitiator,
                  session_initiator,
                  8);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  VARINT,
                  uint64_t,
                  tracing_session_id,
                  4);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_FtraceConfig,
                  ftrace_config,
                  100);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_InodeFileConfig,
                  inode_file_config,
                  102);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_ProcessStatsConfig,
                  process_stats_config,
                  103);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_SysStatsConfig,
                  sys_stats_config,
                  104);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_HeapprofdConfig,
                  heapprofd_config,
                  105);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_JavaHprofConfig,
                  java_hprof_config,
                  110);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidPowerConfig,
                  android_power_config,
                  106);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidLogConfig,
                  android_log_config,
                  107);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_GpuCounterConfig,
                  gpu_counter_config,
                  108);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidGameInterventionListConfig,
                  android_game_intervention_list_config,
                  116);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_PackagesListConfig,
                  packages_list_config,
                  109);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_PerfEventConfig,
                  perf_event_config,
                  111);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_VulkanMemoryConfig,
                  vulkan_memory_config,
                  112);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_TrackEventConfig,
                  track_event_config,
                  113);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidPolledStateConfig,
                  android_polled_state_config,
                  114);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidSystemPropertyConfig,
                  android_system_property_config,
                  118);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_StatsdTracingConfig,
                  statsd_tracing_config,
                  117);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_SystemInfoConfig,
                  system_info_config,
                  119);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_ChromeConfig,
                  chrome_config,
                  101);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_V8Config,
                  v8_config,
                  127);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_InterceptorConfig,
                  interceptor_config,
                  115);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_NetworkPacketTraceConfig,
                  network_packet_trace_config,
                  120);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_SurfaceFlingerLayersConfig,
                  surfaceflinger_layers_config,
                  121);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_SurfaceFlingerTransactionsConfig,
                  surfaceflinger_transactions_config,
                  123);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidSdkSyspropGuardConfig,
                  android_sdk_sysprop_guard_config,
                  124);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_EtwConfig,
                  etw_config,
                  125);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_ProtoLogConfig,
                  protolog_config,
                  126);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_AndroidInputEventConfig,
                  android_input_event_config,
                  128);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_PixelModemConfig,
                  pixel_modem_config,
                  129);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  STRING,
                  const char*,
                  legacy_config,
                  1000);
DEJAVIEW_PB_FIELD(dejaview_protos_DataSourceConfig,
                  MSG,
                  dejaview_protos_TestConfig,
                  for_testing,
                  1001);

#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_CONFIG_DATA_SOURCE_CONFIG_PZC_H_
