/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_ANDROID_ANDROID_TRACK_EVENT_PZC_H_
#define INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_ANDROID_ANDROID_TRACK_EVENT_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "dejaview/public/pb_macros.h"
#include "dejaview/public/protos/trace/track_event/track_event.pzc.h"

DEJAVIEW_PB_EXTENSION_FIELD(dejaview_protos_AndroidTrackEvent,
                            dejaview_protos_TrackEvent,
                            STRING,
                            const char*,
                            binder_service_name,
                            2001);
DEJAVIEW_PB_EXTENSION_FIELD(dejaview_protos_AndroidTrackEvent,
                            dejaview_protos_TrackEvent,
                            STRING,
                            const char*,
                            binder_interface_name,
                            2002);
DEJAVIEW_PB_EXTENSION_FIELD(dejaview_protos_AndroidTrackEvent,
                            dejaview_protos_TrackEvent,
                            STRING,
                            const char*,
                            apex_name,
                            2003);
#endif  // INCLUDE_DEJAVIEW_PUBLIC_PROTOS_TRACE_ANDROID_ANDROID_TRACK_EVENT_PZC_H_
